name: SSH Login

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  ssh-login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install paramiko requests
      
      - name: Run Python script
        env:
          SSH_INFO: ${{ secrets.SSH_INFO }}
          COMMAND: ${{ secrets.COMMAND }}
          PUSHURL: ${{ secrets.PUSHURL }}
          USERID: ${{ secrets.USERID }}
          USERTYPE: ${{ secrets.USERTYPE }}
          
        run: python run.py
